AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-rest-to-http-api-migration

  SAM Template describing the way to implement a basic serverless service using an HTTP API

Parameters:
  DynamoDBTableName:
    Type: String
    Default: http-item-table
  S3BucketName:
    Type: String
    Default: http-example-bucket

Globals:
  Function:
    Runtime: nodejs12.x
    Tracing: Active
    Timeout: 3

Resources:
  HTTPApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: !Join [ '', [ 's3://', !Ref S3BucketName, '/example-openapi-spec.yaml' ] ]

  AddItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/HTTP/add-item/
      Handler: app.lambdaHandler
      Role: !GetAtt AddItemRole.Arn
      Environment:
        Variables:
          TableName: !Ref ItemTable
      Events:
        AddItemEvent:
          Type: HttpApi
          Properties:
            Path: /items
            Method: POST

  AddItemRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AddItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt ItemTable.Arn
              - Effect: Allow
                Action:
                  - xray:PutTelemetryRecords
                  - xray:PutTraceSegments
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/HTTP/get-item/
      Handler: app.lambdaHandler
      Role: !GetAtt GetItemRole.Arn
      Environment:
        Variables:
          TableName: !Ref ItemTable
      Events:
        GetItemEvent:
          Type: HttpApi
          Properties:
            Path: /items/{itemId}
            Method: GET

  GetItemRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: GetItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt ItemTable.Arn
              - Effect: Allow
                Action:
                  - xray:PutTelemetryRecords
                  - xray:PutTraceSegments
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/HTTP/update-item/
      Handler: app.lambdaHandler
      Role: !GetAtt UpdateItemRole.Arn
      Environment:
        Variables:
          TableName: !Ref ItemTable
      Events:
        UpdateItemEvent:
          Type: HttpApi
          Properties:
            Path: /items/{itemId}
            Method: PUT

  UpdateItemRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: UpdateItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt ItemTable.Arn
              - Effect: Allow
                Action:
                  - xray:PutTelemetryRecords
                  - xray:PutTraceSegments
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/HTTP/delete-item/
      Handler: app.lambdaHandler
      Role: !GetAtt DeleteItemRole.Arn
      Environment:
        Variables:
          TableName: !Ref ItemTable
      Events:
        DeleteItemEvent:
          Type: HttpApi
          Properties:
            Path: /items/{itemId}
            Method: DELETE

  DeleteItemRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: DeleteItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                Resource: !GetAtt ItemTable.Arn
              - Effect: Allow
                Action:
                  - xray:PutTelemetryRecords
                  - xray:PutTraceSegments
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute

  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
